export const SET_GEO_LOCATION = "SET_GEO_LOCATION";
export const LOADING_GEO_LOCATION = "LOADING_GEO_LOCATION";
export const ERROR_GEO_LOCATION = "ERROR_GEO_LOCATION";

export const SET_GEO_POSITION_KEY = "SET_GEO_POSITION_KEY";
export const LOADING_GEO_POSITION_KEY = "LOADING_GEO_POSITION_KEY";
export const ERROR_GEO_POSITION_KEY = "LOADING_GEO_POSITION_KEY";

export const SET_AUTO_COMPLETE = "SET_AUTO_COMPLETE";
export const LOADING_AUTO_COMPLETE = "LOADING_AUTO_COMPLETE";
export const ERROR_AUTO_COMPLETE = "ERROR_AUTO_COMPLETE";

export const SET_WEATHER_BY_KEY = "SET_WEATHER_BY_KEY";
export const LOADING_WEATHER_BY_KEY = "LOADING_WEATHER_BY_KEY";
export const ERROR_WEATHER_BY_KEY = "ERROR_WEATHER_BY_KEY";

export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const NOTIFICATION_ADD_FAVORITES_SUCCESS = "NOTIFICATION_ADD_FAVORITES_SUCCESS";
export const NOTIFICATION_REMOVE_FAVORITES_SUCCESS = "NOTIFICATION_REMOVE_FAVORITES_SUCCESS";


export const SET_FAVORITES = "SET_FAVORITES";
export const LOADING_FAVORITES_WAETHER = "LOADING_FAVORITES_WAETHER";
export const SET_FAVORITES_WEATHER = "SET_FAVORITES_WEATHER";
export const ERROR_FAVORITES_WAETHER = "ERROR_FAVORITES_WAETHER";

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const CHANGE_DEGREE_TYPE = 'CHANGE_DEGREE_TYPE';